source clear_data.sql
source direct_nic_handles.sql
source direct_domains_0.sql
source direct_domains_1.sql
source direct_domains_2.sql
source direct_domains_3.sql
source direct_domains_4.sql
source direct_example_data.sql
source registrar_nic_handles.sql
source registrar_domains_0.sql
source registrar_domains_1.sql
source registrar_domains_2.sql
source registrar_domains_3.sql
source registrar_domains_4.sql
source registrar_domains_5.sql
source registrar_domains_6.sql
source registrar_domains_7.sql
source registrar_domains_8.sql
source registrar_domains_9.sql
source registrar_domains_autorenew.sql
source registrar_secondary_market_5.sql
source registrar_secondary_market_6.sql
source registrar_example_data.sql
source nv_nic_handles.sql
source nv_domains_0.sql
source nv_domains_1.sql
source nv_domains_2.sql
source nv_domains_3.sql
source nv_domains_4.sql
source nv_domains_5.sql
source nv_domains_6.sql
source nv_domains_7.sql
source nv_domains_8.sql
source nv_domains_9.sql
source nv_secondary_market.sql
source nv_example_data.sql
