INSERT INTO `SecondaryMarketBuyRequest` VALUES
  (NULL, 'example0604.ie', NULL, 'XBC189-IEDR', 600, 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTNT400JHB1O', NOW(), 'Passed', NULL, 1),
  (NULL, 'example0605.ie', NULL, 'XBC189-IEDR', 600, 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTZCRVHNGN1B', NOW(), 'Passed', NULL, 1),
  (NULL, 'example0606.ie', NULL, 'XBC189-IEDR', 600, 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTFGCEJJPWL9', NOW(), 'Passed', NULL, 1),
  (NULL, 'example0607.ie', NULL, 'XBC189-IEDR', 600, 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RT5S7E9Y9JJO', NOW(), 'Passed', NULL, 1),
  (NULL, 'example0608.ie', NULL, 'XBC189-IEDR', 600, 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTO2E6RIWXY1', NOW(), 'Passed', NULL, 1),
  (NULL, 'example0609.ie', NULL, 'XBC189-IEDR', 600, 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTD94LTWZTC0', NOW(), 'Passed', NULL, 1);
INSERT INTO `SecondaryMarketBuyRequestTelecom` VALUES
  ((SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0604.ie'), '+35312345344', 'Phone', 0),
  ((SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0605.ie'), '+35312345345', 'Phone', 0),
  ((SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0606.ie'), '+35312345346', 'Phone', 0),
  ((SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0607.ie'), '+35312345347', 'Phone', 0),
  ((SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0608.ie'), '+35312345348', 'Phone', 0),
  ((SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0609.ie'), '+35312345349', 'Phone', 0);
INSERT INTO `SecondaryMarketBuyRequestHist` VALUES
  (NULL, NOW(), 'XBC189-IEDR', (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0604.ie'), (SELECT Chng_ID FROM Domain WHERE D_Name = 'example0604.ie'), NULL, (SELECT Chng_ID FROM NicHandle WHERE Nic_Handle = 'XBC189-IEDR'), (SELECT Chng_ID FROM Account WHERE A_Number = 600), 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTNT400JHB1O', NOW(), 'Passed', NULL),
  (NULL, NOW(), 'XBC189-IEDR', (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0605.ie'), (SELECT Chng_ID FROM Domain WHERE D_Name = 'example0605.ie'), NULL, (SELECT Chng_ID FROM NicHandle WHERE Nic_Handle = 'XBC189-IEDR'), (SELECT Chng_ID FROM Account WHERE A_Number = 600), 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTZCRVHNGN1B', NOW(), 'Passed', NULL),
  (NULL, NOW(), 'XBC189-IEDR', (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0606.ie'), (SELECT Chng_ID FROM Domain WHERE D_Name = 'example0606.ie'), NULL, (SELECT Chng_ID FROM NicHandle WHERE Nic_Handle = 'XBC189-IEDR'), (SELECT Chng_ID FROM Account WHERE A_Number = 600), 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTFGCEJJPWL9', NOW(), 'Passed', NULL),
  (NULL, NOW(), 'XBC189-IEDR', (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0607.ie'), (SELECT Chng_ID FROM Domain WHERE D_Name = 'example0607.ie'), NULL, (SELECT Chng_ID FROM NicHandle WHERE Nic_Handle = 'XBC189-IEDR'), (SELECT Chng_ID FROM Account WHERE A_Number = 600), 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RT5S7E9Y9JJO', NOW(), 'Passed', NULL),
  (NULL, NOW(), 'XBC189-IEDR', (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0608.ie'), (SELECT Chng_ID FROM Domain WHERE D_Name = 'example0608.ie'), NULL, (SELECT Chng_ID FROM NicHandle WHERE Nic_Handle = 'XBC189-IEDR'), (SELECT Chng_ID FROM Account WHERE A_Number = 600), 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTO2E6RIWXY1', NOW(), 'Passed', NULL),
  (NULL, NOW(), 'XBC189-IEDR', (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0609.ie'), (SELECT Chng_ID FROM Domain WHERE D_Name = 'example0609.ie'), NULL, (SELECT Chng_ID FROM NicHandle WHERE Nic_Handle = 'XBC189-IEDR'), (SELECT Chng_ID FROM Account WHERE A_Number = 600), 'New Test Holder', NULL, 1, NULL, 1, NULL, 'Test Remark', 'Hostmaster Remark', 'New Admin', NULL, 'email@iedr.ie', NULL, 'Test Inc.', NULL, 'Test Street 1', NULL, 119, NULL, 2, NULL, NULL, NULL, NOW() - INTERVAL 14 DAY, 'RTD94LTWZTC0', NOW(), 'Passed', NULL);
INSERT INTO `SecondaryMarketBuyRequestTelecomHist` VALUES
  ((SELECT MAX(`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` WHERE `Id` = (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0604.ie')), '+35312345344', 'Phone', 0),
  ((SELECT MAX(`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` WHERE `Id` = (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0605.ie')), '+35312345345', 'Phone', 0),
  ((SELECT MAX(`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` WHERE `Id` = (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0606.ie')), '+35312345346', 'Phone', 0),
  ((SELECT MAX(`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` WHERE `Id` = (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0607.ie')), '+35312345347', 'Phone', 0),
  ((SELECT MAX(`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` WHERE `Id` = (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0608.ie')), '+35312345348', 'Phone', 0),
  ((SELECT MAX(`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` WHERE `Id` = (SELECT MAX(`Id`) FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0609.ie')), '+35312345349', 'Phone', 0);
UPDATE `SecondaryMarketBuyRequest` BR SET `Chng_ID` = (SELECT MAX(`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` WHERE `Id` = BR.`Id`) WHERE `D_Name` IN ('example0604.ie', 'example0605.ie', 'example0606.ie', 'example0607.ie', 'example0608.ie', 'example0609.ie');

INSERT INTO `SecondaryMarketSellRequest` VALUES
  (NULL, 'XBC189-IEDR', CURDATE() - INTERVAL 1 DAY, 'Processing', (SELECT `Id` FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0605.ie'), 1),
  (NULL, 'XBC189-IEDR', CURDATE() - INTERVAL 1 DAY, 'Processing', (SELECT `Id` FROM `SecondaryMarketBuyRequest` WHERE `D_Name` = 'example0606.ie'), 1);
INSERT INTO `SecondaryMarketSellRequestHist` VALUES
  (NULL, NOW() - INTERVAL 1 DAY, 'XBC189-IEDR', (SELECT SR.`Id` FROM `SecondaryMarketSellRequest` SR JOIN `SecondaryMarketBuyRequest` BR ON SR.`BuyRequest_Id` = BR.`Id` WHERE BR.`D_Name` = 'example0605.ie'), (SELECT MAX(`Chng_ID`) FROM `NicHandle` WHERE `Nic_Handle` = 'XBC189-IEDR'), NOW() - INTERVAL 1 DAY, 'Processing', (SELECT MAX(BR.`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` BR JOIN `DomainHist` D ON BR.`Domain_Chng_Id` = D.`Chng_ID` WHERE D.`D_Name` = 'example0605.ie')),
  (NULL, NOW() - INTERVAL 1 DAY, 'XBC189-IEDR', (SELECT SR.`Id` FROM `SecondaryMarketSellRequest` SR JOIN `SecondaryMarketBuyRequest` BR ON SR.`BuyRequest_Id` = BR.`Id` WHERE BR.`D_Name` = 'example0606.ie'), (SELECT MAX(`Chng_ID`) FROM `NicHandle` WHERE `Nic_Handle` = 'XBC189-IEDR'), NOW() - INTERVAL 1 DAY, 'Processing', (SELECT MAX(BR.`Chng_ID`) FROM `SecondaryMarketBuyRequestHist` BR JOIN `DomainHist` D ON BR.`Domain_Chng_Id` = D.`Chng_ID` WHERE D.`D_Name` = 'example0606.ie'));
UPDATE `SecondaryMarketSellRequest` SR SET `Chng_ID` = (SELECT MAX(`Chng_ID`) FROM `SecondaryMarketSellRequestHist` WHERE `Id` = SR.`Id`) WHERE `BuyRequest_Id` IN (SELECT `Id` FROM `SecondaryMarketBuyRequest` WHERE `D_Name` IN ('example0605.ie', 'example0606.ie'));

