-- Email templates that used BILL-C_* for transfer tickets. Should be using only
-- gaining / loosing bill c.
--
-- 8,9,10 - XFer Reservation from deposit - look good, created directly
--
-- F 17 Transfer Request (NRP Domain) $DOMAIN$
-- F 18 Transfer Request (NRP Domain) $DOMAIN$ - Failed (IM)
-- F 19 Transfer Request (NRP Domain) $DOMAIN$ - Failed (VM)
--
-- -- all below should be based on gaining?
-- F 33 - Billing Transfer Request Received Re: $DOMAIN$
-- F 35 - (probably bad template!) Who should be in E_CC ?? Losing? Gaining?
-- F 36 - looks ok, send to gaining (like 33)
--
-- 38 - looks good, but looks like send should be based on gaining
--
-- 39 - "Dear Tech-c", to: gaining, cc:losing,admin  ???
--
-- 83 - Should use losing instead of billc
--
-- 84 - Should use gaining instead of billc
--
-- 184 - Excluded from 39 for bulk transfers
--
-- (41,42 - "17 days" hardcoded)

UPDATE `Email` SET `E_Text`=' Dear $ADMIN-C_NAME$\n\nThis notification is to inform you that we have received an application requesting the transfer of your domain name $DOMAIN$ from $LOSING_BILL-C_NAME$ to $GAINING_BILL-C_NAME$. \n\nAs this domain name was currently in the IE Domain Registry Non Renewal Process.  If the transfer request fails this domain name will automatically revert back to $LOSING_BILL-C_NAME$ and be re-entered into the Non Renewal Process.  Please note we will send you notification in this case.\n\n\nKind Regards \nIE Domain Registry Limited\nWeb: www.iedr.ie\n       \n---------------------------------------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n---------------------------------------------------------------------------------------------------------------------------------------\n\n\n', `E_CC`='$LOSING_BILL-C_EMAIL$, $GAINING_BILL-C_EMAIL$' WHERE `E_ID`='17';
UPDATE `Email` SET `E_Text`=' Dear $ADMIN-C_NAME$\n\nThis notification is to inform you that the transfer request received from $GAINING_BILL-C_NAME$ for the domain name $DOMAIN$ has failed.\n\nAs such this domain name is still with your current provider $LOSING_BILL-C_NAME$ and has now been re-entered into the IE Domain Registry Non Renewal Process (NRP).  You will receive further notification shortly outlining the options available to you.  \n\n \nKind Regards \nIE Domain Registry Limited\nWeb: www.iedr.ie\n       \n---------------------------------------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n---------------------------------------------------------------------------------------------------------------------------------------\n\n', `E_CC`='$LOSING_BILL-C_EMAIL$, $GAINING_BILL-C_EMAIL$,' WHERE `E_ID`='18';
UPDATE `Email` SET `E_Text`='  Dear $ADMIN-C_NAME$\n\nThis notification is to inform you that the transfer request received from $GAINING_BILL-C_NAME$ for the domain name $DOMAIN$ has failed.\n\nAs such this domain name is still with your current provider $LOSING_BILL-C_NAME$ and has now been re-entered into the IE Domain Registry Non Renewal Process (NRP). You will receive further notification shortly outlining the options available to you.  \n\n \n\n\nKind Regards \nIE Domain Registry Limited\nWeb: www.iedr.ie\n       \n---------------------------------------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n---------------------------------------------------------------------------------------------------------------------------------------\n\n\n\n\n', `E_CC`='$LOSING_BILL-C_EMAIL$, $GAINING_BILL-C_EMAIL$,' WHERE `E_ID`='19';
UPDATE `Email` SET `E_CC`='$LOSING_BILL-C_EMAIL$, $ADMIN-C_EMAIL$' WHERE `E_ID`='33';
UPDATE `Email` SET `E_CC`='$GAINING_BILL-C_EMAIL$,' WHERE `E_ID`='35';
UPDATE `Email` SET `E_Text`='\n\nPLEASE DO NOT REPLY TO THIS EMAIL. THIS IS AN AUTOMATED EMAIL\n\nDear $ADMIN-C_NAME$\n\nApplication to transfer $DOMAIN$ from $LOSING_BILL-C_NAME$ to $GAINING_BILL-C_NAME$ has now expired.\n\nThe domain name $DOMAIN$ remains with your current Billing Agent $LOSING_BILL-C_NAME$.\n\n\nKind Regards\nRegistration Services Team\nIE Domain Registry Limited\nTel:  +353 (1) 2365400\nFax: +353 (1) 2300365\nWeb: www.iedr.ie\n\n\n-------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n-------------------------------------------------------------------------------------------------------\n\n\n\n', `E_CC`='$LOSING_BILL-C_EMAIL$, $GAINING_BILL-C_EMAIL$' WHERE `E_ID`='83';

-- CRS-105

DELETE FROM `App_Config` WHERE `Cfg_Key` = 'email_attempt_limit';

INSERT INTO `App_Config` VALUES
('email_attempt_limit', 'INT', 10);

INSERT INTO `Email` (`E_ID`, `E_Name`, `E_Text`, `E_Subject`, `E_To`, `E_From`, `active`, `Html`, `E_Suppressible`, `EG_ID`) VALUES
('185', 'ErrorWhileSendingEmail', 'The limit of attempts of sending the email was reached, the following email was not sent:\n\n$EMAIL_TEXT$\n\n Check the logs for the details. \n\r$EMAIL_LOGS$\n\r', 'Fatal error while sending email: $EMAIL_SUBJECT$ - check the logs for the details', 'asd@iedr.ie', 'asd@iedr.ie', '1', '0', 'N', 14);

-- CRS-107

UPDATE `Email` SET `E_From` = 'registrations@iedr.ie' where `E_ID` in (49, 105);
UPDATE `Email` SET `E_From` = 'asd@iedr.ie' where `E_ID` in (56, 150, 160, 161, 175, 900, 901, 902);
ALTER TABLE `Email` MODIFY `E_From` TEXT NOT NULL;

-- CRS-122

UPDATE `Email` SET `E_Text`= REPLACE(`E_Text`, '$BILL-C_NAME$', '$GAINING_BILL-C_NAME$'), `E_To` = '$GAINING_BILL-C_EMAIL$' WHERE `E_ID`='84';
INSERT INTO `Email` (`E_ID`, `E_Name`, `E_Text`, `E_Subject`, `E_To`, `E_CC`, `E_From`, `E_CC_Internal`, `E_BCC_Internal`, `EG_ID`, `E_Suppressible`) VALUES
(184, 'BulkTransferNotification', '\n\nPLEASE DO NOT REPLY TO THIS EMAIL. THIS IS AN AUTOMATED EMAIL\n\nDear $ADMIN-C_NAME$\n\nThe domain name: $DOMAIN$ held by $HOLDER$, has been transferred from former Billing Contact $LOSING_BILL-C_NAME$ to your new Billing Contact, $GAINING_BILL-C_NAME$ as a part of a bulk transfer.\n\nFor any queries related to your domain name please contact your new registrar, $GAINING_BILL-C_NAME$.\n\n\nKind Regards\nRegistration Services Team\nIE Domain Registry Limited\nTel:  +353 (1) 2365400\nFax: +353 (1) 2300365\nWeb: www.iedr.ie\n\n\n-------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n-------------------------------------------------------------------------------------------------------\n\n\n\n', 'Bulk Transfer Completed Re: $DOMAIN$', '$GAINING_BILL-C_EMAIL$', '$ADMIN-C_EMAIL$, $LOSING_BILL-C_EMAIL$', 'registrations@iedr.ie', 'registrations@iedr.ie', 'hostmaster-archive@domainregistry.ie', 11, 'N');

-- CRS-514 - removing source code related to Suspension Notification

ALTER TABLE `Domain_Notifications` DROP COLUMN `Type`;

-- CRS-220 IPv6
ALTER TABLE DNS     CHANGE COLUMN DNS_IpAddr DNS_IPv4_Addr varchar(15), ADD COLUMN DNS_IPv6_Addr varchar(45) AFTER DNS_IPv4_Addr;
ALTER TABLE DNSHist CHANGE COLUMN DNS_IpAddr DNS_IPv4_Addr varchar(15), ADD COLUMN DNS_IPv6_Addr varchar(45) AFTER DNS_IPv4_Addr;

ALTER TABLE TicketNameserver     CHANGE TN_IP TN_IPv4 varchar(15), CHANGE TN_IP_Fail_Cd TN_IPv4_Fail_Cd tinyint(3), ADD TN_IPv6 varchar(45) AFTER TN_IPv4_Fail_Cd, ADD TN_IPv6_Fail_Cd tinyint(3) AFTER TN_IPv6;
ALTER TABLE TicketNameserverHist CHANGE TN_IP TN_IPv4 varchar(15), CHANGE TN_IP_Fail_Cd TN_IPv4_Fail_Cd tinyint(3), ADD TN_IPv6 varchar(45) AFTER TN_IPv4_Fail_Cd, ADD TN_IPv6_Fail_Cd tinyint(3) AFTER TN_IPv6;

ALTER TABLE IE_Zone_DNS MODIFY IPv4_Addr varchar(15), MODIFY IPv6_Addr varchar(45);

-- CRS-218 -- Making list of top level domains configurable

DROP TABLE IF EXISTS `TopLevelDomain`;
CREATE TABLE `TopLevelDomain` (
  `Name` VARCHAR(64) PRIMARY KEY);

INSERT INTO `TopLevelDomain` VALUES
('ABOGADO'),
('AC'),
('ACADEMY'),
('ACCOUNTANTS'),
('ACTOR'),
('AD'),
('AE'),
('AERO'),
('AF'),
('AG'),
('AGENCY'),
('AI'),
('AIRFORCE'),
('AL'),
('AM'),
('AN'),
('AO'),
('AQ'),
('AR'),
('ARCHI'),
('ARMY'),
('ARPA'),
('AS'),
('ASIA'),
('ASSOCIATES'),
('AT'),
('ATTORNEY'),
('AU'),
('AUDIO'),
('AW'),
('AX'),
('AXA'),
('AZ'),
('BA'),
('BAR'),
('BARGAINS'),
('BAYERN'),
('BB'),
('BD'),
('BE'),
('BEER'),
('BERLIN'),
('BF'),
('BG'),
('BH'),
('BI'),
('BID'),
('BIKE'),
('BIO'),
('BIZ'),
('BJ'),
('BLACK'),
('BLACKFRIDAY'),
('BLUE'),
('BM'),
('BMW'),
('BN'),
('BNPPARIBAS'),
('BO'),
('BOUTIQUE'),
('BR'),
('BRUSSELS'),
('BS'),
('BT'),
('BV'),
('BUILD'),
('BUILDERS'),
('BUSINESS'),
('BUZZ'),
('BW'),
('BY'),
('BZ'),
('BZH'),
('CA'),
('CAB'),
('CAMERA'),
('CAMP'),
('CAPETOWN'),
('CAPITAL'),
('CARDS'),
('CARE'),
('CAREERS'),
('CASH'),
('CAT'),
('CATERING'),
('CC'),
('CD'),
('CENTER'),
('CEO'),
('CF'),
('CG'),
('CH'),
('CHEAP'),
('CHRISTMAS'),
('CHURCH'),
('CI'),
('CITIC'),
('CITY'),
('CK'),
('CL'),
('CLAIMS'),
('CLEANING'),
('CLINIC'),
('CLOTHING'),
('CLUB'),
('CM'),
('CN'),
('CO'),
('CODES'),
('COFFEE'),
('COLLEGE'),
('COLOGNE'),
('COM'),
('COMMUNITY'),
('COMPANY'),
('COMPUTER'),
('CONDOS'),
('CONSTRUCTION'),
('CONSULTING'),
('CONTRACTORS'),
('COOKING'),
('COOL'),
('COOP'),
('COUNTRY'),
('CR'),
('CREDIT'),
('CREDITCARD'),
('CRUISES'),
('CU'),
('CV'),
('CW'),
('CX'),
('CY'),
('CYMRU'),
('CZ'),
('DANCE'),
('DATE'),
('DATING'),
('DE'),
('DEALS'),
('DEMOCRAT'),
('DENTAL'),
('DESI'),
('DIAMONDS'),
('DIGITAL'),
('DIRECT'),
('DIRECTORY'),
('DISCOUNT'),
('DJ'),
('DK'),
('DM'),
('DO'),
('DOMAINS'),
('DURBAN'),
('DZ'),
('EC'),
('EDU'),
('EDUCATION'),
('EE'),
('EG'),
('EH'),
('EMAIL'),
('ENGINEERING'),
('ENTERPRISES'),
('EQUIPMENT'),
('ER'),
('ES'),
('ESTATE'),
('ET'),
('EU'),
('EUS'),
('EVENTS'),
('EXCHANGE'),
('EXPERT'),
('EXPOSED'),
('FAIL'),
('FARM'),
('FI'),
('FINANCE'),
('FINANCIAL'),
('FISH'),
('FISHING'),
('FITNESS'),
('FJ'),
('FK'),
('FLIGHTS'),
('FLORIST'),
('FM'),
('FO'),
('FOO'),
('FOUNDATION'),
('FR'),
('FRL'),
('FROGANS'),
('FUND'),
('FURNITURE'),
('FUTBOL'),
('GA'),
('GAL'),
('GALLERY'),
('GB'),
('GD'),
('GE'),
('GENT'),
('GF'),
('GG'),
('GH'),
('GI'),
('GIFT'),
('GIFTS'),
('GL'),
('GLASS'),
('GLOBAL'),
('GLOBO'),
('GM'),
('GN'),
('GOP'),
('GOV'),
('GP'),
('GQ'),
('GR'),
('GRAPHICS'),
('GRATIS'),
('GRIPE'),
('GS'),
('GT'),
('GU'),
('GUIDE'),
('GUITARS'),
('GURU'),
('GW'),
('GY'),
('HAMBURG'),
('HAUS'),
('HEALTH'),
('HEALTHCARE'),
('HIPHOP'),
('HIV'),
('HK'),
('HM'),
('HN'),
('HOLDINGS'),
('HOLIDAY'),
('HORSE'),
('HOST'),
('HOUSE'),
('HR'),
('HT'),
('HU'),
('ID'),
('IE'),
('IL'),
('IM'),
('IMMO'),
('IMMOBILIEN'),
('IN'),
('INDUSTRIES'),
('INFO'),
('INK'),
('INSTITUTE'),
('INSURE'),
('INT'),
('INTERNATIONAL'),
('INVESTMENTS'),
('IO'),
('IQ'),
('IR'),
('IS'),
('IT'),
('JE'),
('JETZT'),
('JM'),
('JO'),
('JOBS'),
('JOBURG'),
('JP'),
('JUEGOS'),
('KAUFEN'),
('KE'),
('KG'),
('KH'),
('KI'),
('KIM'),
('KITCHEN'),
('KIWI'),
('KM'),
('KN'),
('KOELN'),
('KP'),
('KR'),
('KW'),
('KY'),
('KZ'),
('LA'),
('LAND'),
('LAWYER'),
('LB'),
('LC'),
('LEASE'),
('LI'),
('LIFE'),
('LIGHTING'),
('LIMITED'),
('LIMO'),
('LINK'),
('LK'),
('LOANS'),
('LONDON'),
('LR'),
('LS'),
('LT'),
('LTDA'),
('LU'),
('LUXURY'),
('LV'),
('LY'),
('MA'),
('MAISON'),
('MANAGEMENT'),
('MANGO'),
('MARKET'),
('MARKETING'),
('MC'),
('MD'),
('ME'),
('MEDIA'),
('MELBOURNE'),
('MENU'),
('MG'),
('MH'),
('MIL'),
('MINI'),
('MK'),
('ML'),
('MM'),
('MN'),
('MO'),
('MOBI'),
('MODA'),
('MOE'),
('MONASH'),
('MORTGAGE'),
('MOSCOW'),
('MP'),
('MQ'),
('MR'),
('MS'),
('MT'),
('MU'),
('MUSEUM'),
('MV'),
('MW'),
('MX'),
('MY'),
('MZ'),
('NA'),
('NAGOYA'),
('NAME'),
('NAVY'),
('NC'),
('NE'),
('NET'),
('NETWORK'),
('NEUSTAR'),
('NF'),
('NG'),
('NI'),
('NINJA'),
('NL'),
('NO'),
('NP'),
('NR'),
('NU'),
('NYC'),
('NZ'),
('OKINAWA'),
('OM'),
('ONL'),
('OOO'),
('ORG'),
('ORGANIC'),
('OVH'),
('PA'),
('PARIS'),
('PARTNERS'),
('PARTS'),
('PE'),
('PF'),
('PG'),
('PH'),
('PHOTO'),
('PHOTOGRAPHY'),
('PHOTOS'),
('PHYSIO'),
('PICS'),
('PICTURES'),
('PINK'),
('PIZZA'),
('PK'),
('PL'),
('PLACE'),
('PLUMBING'),
('PM'),
('PN'),
('POST'),
('PR'),
('PRESS'),
('PRO'),
('PRODUCTIONS'),
('PRODUCTS'),
('PROPERTIES'),
('PS'),
('PT'),
('PUB'),
('PW'),
('PY'),
('QA'),
('QUEBEC'),
('RE'),
('REALTOR'),
('RECIPES'),
('RED'),
('REISE'),
('REISEN'),
('REN'),
('RENTALS'),
('REPAIR'),
('REPORT'),
('REPUBLICAN'),
('REST'),
('RESTAURANT'),
('REVIEWS'),
('RICH'),
('RO'),
('ROCKS'),
('RODEO'),
('RS'),
('RU'),
('RUHR'),
('RW'),
('SA'),
('SAARLAND'),
('SARL'),
('SB'),
('SC'),
('SCA'),
('SCB'),
('SCOT'),
('SCHULE'),
('SD'),
('SE'),
('SERVICES'),
('SEXY'),
('SG'),
('SH'),
('SHIKSHA'),
('SHOES'),
('SI'),
('SINGLES'),
('SJ'),
('SK'),
('SL'),
('SM'),
('SN'),
('SO'),
('SOCIAL'),
('SOLAR'),
('SOLUTIONS'),
('SOY'),
('SPACE'),
('SR'),
('ST'),
('SU'),
('SUPPLIES'),
('SUPPLY'),
('SUPPORT'),
('SURF'),
('SURGERY'),
('SV'),
('SY'),
('SYSTEMS'),
('SZ'),
('TAIPEI'),
('TATAR'),
('TATTOO'),
('TAX'),
('TC'),
('TD'),
('TECHNOLOGY'),
('TEL'),
('TF'),
('TG'),
('TH'),
('TIENDA'),
('TIPS'),
('TJ'),
('TK'),
('TL'),
('TM'),
('TN'),
('TO'),
('TODAY'),
('TOKYO'),
('TOOLS'),
('TOWN'),
('TOYS'),
('TP'),
('TR'),
('TRADE'),
('TRAINING'),
('TRAVEL'),
('TT'),
('TV'),
('TW'),
('TZ'),
('UA'),
('UG'),
('UK'),
('UNIVERSITY'),
('UNO'),
('US'),
('UY'),
('UZ'),
('VA'),
('VACATIONS'),
('VC'),
('VE'),
('VEGAS'),
('VENTURES'),
('VERSICHERUNG'),
('VET'),
('VG'),
('VI'),
('VIAJES'),
('VILLAS'),
('VISION'),
('VLAANDEREN'),
('VN'),
('VODKA'),
('VOTING'),
('VOYAGE'),
('VU'),
('WALES'),
('WANG'),
('WATCH'),
('WEBCAM'),
('WEBSITE'),
('WED'),
('WF'),
('WIEN'),
('WIKI'),
('WORKS'),
('WORLD'),
('WS'),
('WTF'),
('XN'),
('XXX'),
('XYZ'),
('YANDEX'),
('YE'),
('YOKOHAMA'),
('YT'),
('ZA'),
('ZM'),
('ZONE'),
('ZW');

-- CRS-545

DELETE FROM `App_Config` WHERE `Cfg_Key` = 'ticket_expiration_notification_period';

INSERT INTO `App_Config` VALUES
('ticket_expiration_notification_period', 'INT', 10);

UPDATE `Email` SET `E_Text`='\n\nPLEASE DO NOT REPLY TO THIS EMAIL. THIS IS AN AUTOMATED EMAIL\n\n** This is Important ** Please read carefully **\n\nDear $ADMIN-C_NAME$\n\nMore than $TICKET_DAYS_PASSED$ days have passed since an application was submitted to transfer $DOMAIN$ to $GAINING_BILL-C_NAME$.\n\nBilling transfers are usually held up in this way due to a problem with your domains'' hosting. If the transfer request is not completed within $TICKET_DAYS_REMAINING$ days, the request will expire.  The domain name will subsequently remain with your current Registrar $LOSING_BILL-C_NAME$.\n\nPlease contact your hosting provider or new registrar as soon as possible to ensure that any issues are resolved.\n\nKind Regards\nRegistration Services Team\nIE Domain Registry Limited\nTel:  +353 (1) 2365400\nFax: +353 (1) 2300365\nWeb: www.iedr.ie\n\n-------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n-------------------------------------------------------------------------------------------------------\n\n\n' WHERE `E_ID`='35';
UPDATE `Email` SET `E_Text`='\nPLEASE DO NOT REPLY TO THIS EMAIL. THIS IS AN AUTOMATED EMAIL\n\n** This is Important ** Please read carefully **  \n\nDear $ADMIN-C_NAME$  \n\nThank you for your request to modify the domain name $DOMAIN$\n\nMore than $TICKET_DAYS_PASSED$ days have passed since your request was submitted and we have not yet received all of the necessary requirements to complete the modification of this domain name.  \n\nIf the requirements are not received within $TICKET_DAYS_REMAINING$ days, your request will expire and you will need to resubmit your modification.  \n\nFor any queries regarding the requirements to complete your modification, please contact your registrar, $REGISTRAR_NAME$  \n\nKind Regards \nRegistration Services Team \nIE Domain Registry Limited \nTel: +353 (1) 2365400 \nFax: +353 (1) 2300365 \nWeb: www.iedr.ie  \n\n------------------------------------------------------------------------------------------------------- \nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin. \nRegistered in Ireland. No: 315315. \n------------------------------------------------------------------------------------------------------- \n\n' WHERE `E_ID`='41';
UPDATE `Email` SET `E_Text`='\n\nPLEASE DO NOT REPLY TO THIS EMAIL. THIS IS AN AUTOMATED EMAIL\n\n** This is Important ** Please read carefully **\n\nDear $ADMIN-C_NAME$\n\nThank you for your application for the domain name $DOMAIN$\n\nMore than $TICKET_DAYS_PASSED$ days have passed since your application was submitted and we have not yet received all of the necessary requirements to complete the registration of this domain name.\n\nIf the requirements are not received within $TICKET_DAYS_REMAINING$ days, your registration will expire and you will need to resubmit your application.\n\nFor any queries regarding the requirements to complete your registration, please contact your registrar, $REGISTRAR_NAME$\n\nKind Regards\nRegistration Services Team\nIE Domain Registry Limited\nTel:  +353 (1) 2365400\nFax: +353 (1) 2300365\nWeb: www.iedr.ie\n\n\n-------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n-------------------------------------------------------------------------------------------------------\n\n\n' WHERE `E_ID`='42';

INSERT INTO `Email`
VALUES (186, '', '\nPLEASE DO NOT REPLY TO THIS EMAIL. THIS IS AN AUTOMATED EMAIL\n\nRemarks : $REMARK$\n\nKind Regards\nRegistration Services Team\nIE Domain Registry Limited\nTel:  +353 (1) 2365400\nFax: +353 (1) 2300365 \nWeb: www.iedr.ie\n\n-------------------------------------------------------------------------------------------------------\nRegistered Office: Harbour Square, Block 2, 4th Floor, Dun Laoghaire, Co. Dublin.\nRegistered in Ireland. No: 315315.\n-------------------------------------------------------------------------------------------------------\n\n\n', '(Ticket Query) Re: $DOMAIN$ ', '$GAINING_BILL-C_EMAIL$', NULL, NULL, 'registrations@iedr.ie', '1', '0', NULL, 'registrations@iedr.ie', 'hostmaster-archive@domainregistry.ie, registrations@iedr.ie', 7, CURRENT_TIMESTAMP, 'Y', '', '');
