#!/usr/bin/perl -w

# Argument handling: ckdns [ origin ] zone

$zone = pop @ARGV ;

$origin = pop @ARGV ;

$zone =~ tr/A-Z/a-z/ ;

$message = "FATAL: $origin is not authoritative for zone $zone.\n";

%non_authoritative_domains = (
$NON_AUTHORITATIVE_DOMAINS_MAP$
);

if ( exists($non_authoritative_domains{$zone}) ) {
        $dns = $non_authoritative_domains{$zone};
        if ($dns eq "*" || $dns eq $origin) {
                print $message;
        }
}
