DELETE FROM Contact WHERE D_Name LIKE 'uc072%';
DELETE FROM ContactHist WHERE D_Name LIKE 'uc072%';
DELETE FROM DNS WHERE D_Name LIKE 'uc072%';
DELETE FROM DNSHist WHERE D_Name LIKE 'uc072%';
DELETE FROM Domain WHERE D_Name LIKE 'uc072%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc072%';

DELETE FROM Domain_Notifications WHERE D_Name LIKE 'uc072%';

