DELETE FROM Contact WHERE D_Name LIKE 'uc013%';
DELETE FROM Contact WHERE D_Name LIKE 'uc013%';
DELETE FROM DNS WHERE D_Name LIKE 'uc013%';
DELETE FROM DNS WHERE D_Name LIKE 'uc013%';
DELETE FROM Domain WHERE D_Name LIKE 'uc013%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc013%';

