DELETE FROM Contact WHERE D_Name LIKE 'uc047%';
DELETE FROM Contact WHERE D_Name LIKE 'uc047%';
DELETE FROM DNS WHERE D_Name LIKE 'uc047%';
DELETE FROM DNS WHERE D_Name LIKE 'uc047%';
DELETE FROM Domain WHERE D_Name LIKE 'uc047%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc047%';

