DELETE FROM TicketNameserver WHERE T_Number IN (SELECT T_Number FROM Ticket WHERE D_Name LIKE 'uc060%');
DELETE FROM TicketNameserverHist WHERE T_Number IN (SELECT T_Number FROM Ticket WHERE D_Name LIKE 'uc060%');
DELETE FROM Ticket WHERE D_Name LIKE 'uc060%';
DELETE FROM TicketHist WHERE D_Name LIKE 'uc060%';

DELETE FROM Contact WHERE D_Name LIKE 'uc060%';
DELETE FROM Contact WHERE D_Name LIKE 'uc060%';
DELETE FROM DNS WHERE D_Name LIKE 'uc060%';
DELETE FROM DNS WHERE D_Name LIKE 'uc060%';
DELETE FROM Domain WHERE D_Name LIKE 'uc060%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc060%';

