DELETE FROM Contact WHERE D_Name LIKE 'uc010%';
DELETE FROM ContactHist WHERE D_Name LIKE 'uc010%';
DELETE FROM DNS WHERE D_Name LIKE 'uc010%';
DELETE FROM DNSHist WHERE D_Name LIKE 'uc010%';
DELETE FROM Domain WHERE D_Name LIKE 'uc010%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc010%';


