INSERT INTO NicHandleHist VALUES (NULL, 'UC024AA-IEDR', 'Use Case 062 - Test Account', (SELECT MAX(Chng_Id) FROM AccountHist WHERE A_Number = 1), 'Registrar co Limited', '1 The Road, Some Street', 14, 121, 'uc024@iedr.ie','Active', NOW(), NOW(), NOW(),'NO','test data generation','UC024AA-IEDR', 'A', NULL, 'YES', 'PORTAL', NOW());
INSERT INTO NicHandle VALUES ('UC024AA-IEDR', 'Use Case 062 - Test Account', 1, 'Registrar co Limited', '1 The Road, Some Street', 14, 121, 'uc024@iedr.ie','Active', NOW(), NOW(), NOW(),'NO','test data generation','UC024AA-IEDR', 'A', NULL, 'YES', (SELECT MAX(Chng_Id) FROM NicHandleHist WHERE Nic_Handle = 'UC024AA-IEDR'));
INSERT INTO AccessHist VALUES (NULL, (SELECT MAX(Chng_Id) FROM NicHandleHist WHERE Nic_Handle = 'UC024AA-IEDR'), 't1X7oZ2/bFDr0cyVoH442gyNoNSib/a', 2, 'NO', 'PORTAL', NOW(), '.Z805gDk7mXJJfbcIwZJde', CURDATE(), 'NO', 'NO', '');
INSERT INTO Access VALUES ('UC024AA-IEDR', 't1X7oZ2/bFDr0cyVoH442gyNoNSib/a', 2, 'NO', '.Z805gDk7mXJJfbcIwZJde', CURDATE(), 'NO', 'NO', '', (SELECT MAX(A.Chng_Id) FROM AccessHist A JOIN NicHandleHist NH  ON A.Nic_Handle_Chng_Id = NH.Chng_Id WHERE NH.Nic_Handle = 'UC024AA-IEDR'));
INSERT INTO AccountHist VALUES (NULL, 723, 'Test Registrar', (SELECT MAX(Chng_Id) FROM NicHandleHist WHERE Nic_Handle = 'UC024AA-IEDR'), 'www.testregistrar.ie', 'Active', '2011-12-08', '2011-12-08', 'NO', 'NO', '2011-12-08 15:00:49', 'test data generation script', NULL, NOW(), 'UC024AA-IEDR');
INSERT INTO Account VALUES (723, 'Test Registrar', 'UC024AA-IEDR', 'www.testregistrar.ie', 'Active', '2011-12-08', '2011-12-08', 'NO', 'NO', '2011-12-08 15:00:49', 'test data generation script', NULL, (SELECT MAX(Chng_Id) FROM AccountHist WHERE A_Number = 723));
UPDATE NicHandleHist SET Account_Chng_Id = (SELECT MAX(Chng_Id) FROM AccountHist WHERE A_Number = 723) WHERE Nic_Handle = 'UC024AA-IEDR';
UPDATE NicHandle SET A_Number = 723 WHERE Nic_Handle = 'UC024AA-IEDR';
INSERT INTO DepositHist VALUES (NULL, (SELECT MAX(Chng_Id) FROM NicHandleHist WHERE Nic_Handle = 'UC024AA-IEDR'), NOW(), 2000, 2000, '20130109164738-C-1205021', '2000', 'INIT', NULL, NULL, NOW());
INSERT INTO Deposit VALUES ('UC024AA-IEDR', NOW(), 2000, 2000, '20130109164738-C-1205021', '2000', 'INIT', NULL, NULL, (SELECT MAX(D.Chng_Id) FROM DepositHist D JOIN NicHandleHist NH  ON D.Nic_Handle_Chng_Id = NH.Chng_Id WHERE NH.Nic_Handle = 'UC024AA-IEDR'));

