DELETE FROM Contact WHERE D_Name LIKE 'uc061%';
DELETE FROM ContactHist WHERE D_Name LIKE 'uc061%';
DELETE FROM DNS WHERE D_Name LIKE 'uc061%';
DELETE FROM DNSHist WHERE D_Name LIKE 'uc061%';
DELETE FROM Domain WHERE D_Name LIKE 'uc061%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc061%';

DELETE FROM TicketNameserver WHERE T_Number IN (SELECT T_Number FROM Ticket WHERE D_Name LIKE 'uc061%');
DELETE FROM TicketNameserverHist WHERE T_Number IN (SELECT T_Number FROM Ticket WHERE D_Name LIKE 'uc061%');
DELETE FROM Ticket WHERE D_Name LIKE 'uc061%';
DELETE FROM TicketHist WHERE D_Name LIKE 'uc061%';

