DELETE FROM Contact WHERE D_Name LIKE 'uc082%';
DELETE FROM ContactHist WHERE D_Name LIKE 'uc082%';
DELETE FROM DNS WHERE D_Name LIKE 'uc082%';
DELETE FROM DNSHist WHERE D_Name LIKE 'uc082%';
DELETE FROM Domain WHERE D_Name LIKE 'uc082%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc082%';

DELETE FROM Telecom WHERE Nic_Handle LIKE 'YYY00%';
DELETE FROM TelecomHist WHERE Nic_Handle LIKE 'YYY00%';
DELETE FROM Access WHERE Nic_Handle LIKE 'YYY00%';
DELETE FROM AccessHist WHERE Nic_Handle_Chng_ID IN (SELECT Chng_ID FROM NicHandleHist WHERE Nic_Handle LIKE 'YYY00%');
DELETE FROM NicHandle WHERE Nic_Handle LIKE 'YYY00%';
DELETE FROM NicHandleHist WHERE Nic_Handle LIKE 'YYY00%';

