DELETE FROM Contact WHERE D_Name LIKE 'uc081%';
DELETE FROM ContactHist WHERE D_Name LIKE 'uc081%';
DELETE FROM DNS WHERE D_Name LIKE 'uc081%';
DELETE FROM DNSHist WHERE D_Name LIKE 'uc081%';
DELETE FROM Domain WHERE D_Name LIKE 'uc081%';
DELETE FROM DomainHist WHERE D_Name LIKE 'uc081%';

DELETE FROM TicketNameserver WHERE T_Number IN (SELECT T_Number FROM Ticket WHERE D_Name LIKE 'uc081%');
DELETE FROM TicketNameserverHist WHERE T_Number IN (SELECT T_Number FROM Ticket WHERE D_Name LIKE 'uc081%');
DELETE FROM Ticket WHERE D_Name LIKE 'uc081%';
DELETE FROM TicketHist WHERE D_Name LIKE 'uc081%';

DELETE FROM Access WHERE Nic_Handle IN (SELECT Nic_Handle FROM NicHandle WHERE NH_Name LIKE 'UC081%');
DELETE FROM AccessHist WHERE Nic_Handle_Chng_ID IN (SELECT Chng_ID FROM NicHandleHist WHERE NH_Name LIKE 'UC081%');
DELETE FROM NicHandle WHERE NH_Name LIKE 'UC081%';
DELETE FROM NicHandleHist WHERE NH_Name LIKE 'UC081%';

DELETE FROM Telecom WHERE Nic_Handle LIKE 'ZZZ00%';
DELETE FROM TelecomHist WHERE Nic_Handle LIKE 'ZZZ00%';
DELETE FROM Access WHERE Nic_Handle LIKE 'ZZZ00%';
DELETE FROM AccessHist WHERE Nic_Handle_Chng_ID IN (SELECT Chng_ID FROM NicHandleHist WHERE Nic_Handle LIKE 'ZZZ00%');
DELETE FROM NicHandle WHERE Nic_Handle LIKE 'ZZZ00%';
DELETE FROM NicHandleHist WHERE Nic_Handle LIKE 'ZZZ00%';

