#!/bin/sh

#
# This file simply redirects all passed arguments
# to org.checkerframework.framework.util.CheckerMain
#

mydir="`dirname $0`"

if [ -z ${CHECKER_HOME+x} ]; then
  echo "Missing CHECKER_HOME variable in system, aborting"
  exit 1
fi

eval "java" "-jar" "${CHECKER_HOME}"/dist/checker.jar -processorpath "${CHECKER_HOME}"/dist/checker.jar "@${mydir}"/argfile "$@"
